let suggestions = [
    "Architectures",
    "Building",
    "Civil Engineering",
    "Structural Engineering",
    "Construction",
    "Roads and Maps",
    "Sky Scrappers",
    "Apartments",
    "Bungalow",
    "Mosque",
    "Bridge",
    "Highway Constrcution",
    "Building Materials",
    "How to become a web developer",
    "How to start Civil Engineering",
    "How to repair a damaged road",
    "How to build a house in water logged area",
    "How to build a Highway in a congested area",
    "Controlled Access Highway",
    "Boulevard Road",
    "Frontage road",
    "Two-Lane expressway",
    "Trunk Road",
    "Ring Road",
    "Tyes of roads in Kenya",
    "Types of Roads in civil Engineering",
    "Types of roads PPT",
    "Types of roads In UK",
    "Asphalt Roads",
    "Murrum Roads",
    "Tests done before Construction",
    "Architectural Design",
]